version: '2.2'
services:
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch7
    environment:
      - node.name=elasticsearch7
      - discovery.seed_hosts=elasticsearch7node2
      - cluster.initial_master_nodes=elasticsearch7,elasticsearch7node2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/usr/share/dataBackup
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./dataBackup:/usr/share/dataBackup
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch7node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch7node2
    environment:
      - node.name=elasticsearch7node2
      - discovery.seed_hosts=elasticsearch7
      - cluster.initial_master_nodes=elasticsearch7,elasticsearch7node2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=/usr/share/dataBackup
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./dataBackup:/usr/share/dataBackup
    networks:
      - esnet
  kibana7:
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch7:9200
    ports:
      - 5601:5601
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet: